// The @cloudflare/workers-oauth-provider types default their Env generic to
// `Cloudflare.Env`, a namespace normally generated by `wrangler types`. We pass
// our own `Env` explicitly everywhere, but this ambient shim satisfies the
// default-type-parameter references in the library's .d.ts without requiring a
// generated worker-configuration.d.ts in the repo.
declare namespace Cloudflare {
  interface Env {
    [key: string]: unknown;
  }
}
